
import __ASTRO_IMAGE_IMPORT_1SjmwC from "/src/images/blog/1.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F1.md";
import __ASTRO_IMAGE_IMPORT_1aovVP from "/src/images/blog/2.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F2.md";
import __ASTRO_IMAGE_IMPORT_rtFm3 from "/src/images/blog/3.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F3.md";
import __ASTRO_IMAGE_IMPORT_ZgqadJ from "/src/images/blog/4.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F4.md";
import __ASTRO_IMAGE_IMPORT_ZYl0Nw from "/src/images/blog/5.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F5.md";
import __ASTRO_IMAGE_IMPORT_Z1HfQoj from "/src/images/blog/6.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F6.md";
import __ASTRO_IMAGE_IMPORT_1ToEsY from "/src/images/logos/figma.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fwork%2F2.md";
import __ASTRO_IMAGE_IMPORT_Z2p6RrU from "/src/images/logos/jetbrains.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fwork%2F1.md";
import __ASTRO_IMAGE_IMPORT_Z1D0AKl from "/src/images/logos/kayako.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fwork%2F3.md";
import __ASTRO_IMAGE_IMPORT_241VhU from "/src/images/logos/procreate.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fwork%2F6.md";
import __ASTRO_IMAGE_IMPORT_Z1oMIF6 from "/src/images/logos/vscode.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fwork%2F4.md";
import __ASTRO_IMAGE_IMPORT_Z10SeLu from "/src/images/logos/zapier.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fwork%2F5.md";
import __ASTRO_IMAGE_IMPORT_ZdxoUh from "/src/images/team/1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2F2.md";
import __ASTRO_IMAGE_IMPORT_1jEaj6 from "/src/images/team/2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2F1.md";
import __ASTRO_IMAGE_IMPORT_Z2dk0fk from "/src/images/team/3.png?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2F3.md";
export default new Map([["/src/images/blog/1.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F1.md", __ASTRO_IMAGE_IMPORT_1SjmwC], ["/src/images/blog/2.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F2.md", __ASTRO_IMAGE_IMPORT_1aovVP], ["/src/images/blog/3.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F3.md", __ASTRO_IMAGE_IMPORT_rtFm3], ["/src/images/blog/4.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F4.md", __ASTRO_IMAGE_IMPORT_ZgqadJ], ["/src/images/blog/5.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F5.md", __ASTRO_IMAGE_IMPORT_ZYl0Nw], ["/src/images/blog/6.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F6.md", __ASTRO_IMAGE_IMPORT_Z1HfQoj], ["/src/images/logos/figma.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fwork%2F2.md", __ASTRO_IMAGE_IMPORT_1ToEsY], ["/src/images/logos/jetbrains.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fwork%2F1.md", __ASTRO_IMAGE_IMPORT_Z2p6RrU], ["/src/images/logos/kayako.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fwork%2F3.md", __ASTRO_IMAGE_IMPORT_Z1D0AKl], ["/src/images/logos/procreate.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fwork%2F6.md", __ASTRO_IMAGE_IMPORT_241VhU], ["/src/images/logos/vscode.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fwork%2F4.md", __ASTRO_IMAGE_IMPORT_Z1oMIF6], ["/src/images/logos/zapier.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fwork%2F5.md", __ASTRO_IMAGE_IMPORT_Z10SeLu], ["/src/images/team/1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2F2.md", __ASTRO_IMAGE_IMPORT_ZdxoUh], ["/src/images/team/2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2F1.md", __ASTRO_IMAGE_IMPORT_1jEaj6], ["/src/images/team/3.png?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2F3.md", __ASTRO_IMAGE_IMPORT_Z2dk0fk]]);
		